version: '3.2'

services:
  frontend-cfinep:
     build: .
     restart: always
     container_name: frontend-cfinep-dev
     volumes:
       - ./:/usr/src/app
     ports:
       - 8080:8080
     env_file:
       - .env
     command: npm run serve


