version: '3.2'

services:
  mysql-db-cfinep:
    image: mysql:5.7
    container_name: mysql-db-cfinep
    restart: always
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

  phpmyadmin-cfinep:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-cfinep
    restart: always
    links:
      - mysql-db-cfinep
    ports:
      - 8888:80
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - mysql-db-cfinep

  backend-cfinep:
    build: .
    container_name: backend-cfinep
    restart: always
    ports:
       - 3333:3333
    volumes:
       - ./:/usr/src/app
    command: nodemon server.js
    links:
        - mysql-db-cfinep
    depends_on:
      - mysql-db-cfinep

volumes:
  data:


