export default {
    id: null,
    user_id: '',
    nome: '',
    usuario_username: '',
    email: '',
    telefone: '',
    orientador: '',
    nivel_graduacao: '',
    data_para_encerramento_conta: '',
    quantidade_cpus: '',
    quantidade_nos: '',
    quantidade_memoria: '',
    outros_recursos_computacionais: '',
    softwares_solicitados: '',
    ferramentas_utilizadas: '',
    linha_pesquisa: '',
    titulo_projeto: '',
    projeto_financiado: '',
    agencia_financiadora: '',
    projeto_registrado_ufv: '',
    tempo_duracao_projeto_pesquisa: '',
    resumo_objetivo_projeto_pesquisa: '',
    metodologias_utilizadas: '',
    outras_informacoes: '',
}